/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CartilhaRouteImport } from './routes/cartilha'
import { Route as ConsolidadoRouteImport } from './routes/consolidado'
import { Route as RelatorioConsolidadoRouteImport } from './routes/relatorio-consolidado'
import { Route as DiretoriaIndexRouteImport } from './routes/diretoria.index'
import { Route as DiretoriaSlugRouteImport } from './routes/diretoria.$slug'
import { Route as RelatorioSlugRouteImport } from './routes/relatorio.$slug'
import { Route as UnidadeSlugRouteImport } from './routes/unidade.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CartilhaRoute = CartilhaRouteImport.update({
  id: '/cartilha',
  path: '/cartilha',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsolidadoRoute = ConsolidadoRouteImport.update({
  id: '/consolidado',
  path: '/consolidado',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatorioConsolidadoRoute = RelatorioConsolidadoRouteImport.update({
  id: '/relatorio-consolidado',
  path: '/relatorio-consolidado',
  getParentRoute: () => rootRouteImport,
} as any)
const DiretoriaIndexRoute = DiretoriaIndexRouteImport.update({
  id: '/diretoria/',
  path: '/diretoria/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiretoriaSlugRoute = DiretoriaSlugRouteImport.update({
  id: '/diretoria/$slug',
  path: '/diretoria/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatorioSlugRoute = RelatorioSlugRouteImport.update({
  id: '/relatorio/$slug',
  path: '/relatorio/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const UnidadeSlugRoute = UnidadeSlugRouteImport.update({
  id: '/unidade/$slug',
  path: '/unidade/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cartilha': typeof CartilhaRoute
  '/consolidado': typeof ConsolidadoRoute
  '/relatorio-consolidado': typeof RelatorioConsolidadoRoute
  '/diretoria/$slug': typeof DiretoriaSlugRoute
  '/relatorio/$slug': typeof RelatorioSlugRoute
  '/unidade/$slug': typeof UnidadeSlugRoute
  '/diretoria/': typeof DiretoriaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cartilha': typeof CartilhaRoute
  '/consolidado': typeof ConsolidadoRoute
  '/relatorio-consolidado': typeof RelatorioConsolidadoRoute
  '/diretoria/$slug': typeof DiretoriaSlugRoute
  '/relatorio/$slug': typeof RelatorioSlugRoute
  '/unidade/$slug': typeof UnidadeSlugRoute
  '/diretoria': typeof DiretoriaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cartilha': typeof CartilhaRoute
  '/consolidado': typeof ConsolidadoRoute
  '/relatorio-consolidado': typeof RelatorioConsolidadoRoute
  '/diretoria/$slug': typeof DiretoriaSlugRoute
  '/relatorio/$slug': typeof RelatorioSlugRoute
  '/unidade/$slug': typeof UnidadeSlugRoute
  '/diretoria/': typeof DiretoriaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cartilha'
    | '/consolidado'
    | '/relatorio-consolidado'
    | '/diretoria/$slug'
    | '/relatorio/$slug'
    | '/unidade/$slug'
    | '/diretoria/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/cartilha'
    | '/consolidado'
    | '/relatorio-consolidado'
    | '/diretoria/$slug'
    | '/relatorio/$slug'
    | '/unidade/$slug'
    | '/diretoria'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cartilha'
    | '/consolidado'
    | '/relatorio-consolidado'
    | '/diretoria/$slug'
    | '/relatorio/$slug'
    | '/unidade/$slug'
    | '/diretoria/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CartilhaRoute: typeof CartilhaRoute
  ConsolidadoRoute: typeof ConsolidadoRoute
  RelatorioConsolidadoRoute: typeof RelatorioConsolidadoRoute
  DiretoriaSlugRoute: typeof DiretoriaSlugRoute
  RelatorioSlugRoute: typeof RelatorioSlugRoute
  UnidadeSlugRoute: typeof UnidadeSlugRoute
  DiretoriaIndexRoute: typeof DiretoriaIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cartilha': {
      id: '/cartilha'
      path: '/cartilha'
      fullPath: '/cartilha'
      preLoaderRoute: typeof CartilhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consolidado': {
      id: '/consolidado'
      path: '/consolidado'
      fullPath: '/consolidado'
      preLoaderRoute: typeof ConsolidadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorio-consolidado': {
      id: '/relatorio-consolidado'
      path: '/relatorio-consolidado'
      fullPath: '/relatorio-consolidado'
      preLoaderRoute: typeof RelatorioConsolidadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diretoria/': {
      id: '/diretoria/'
      path: '/diretoria'
      fullPath: '/diretoria/'
      preLoaderRoute: typeof DiretoriaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diretoria/$slug': {
      id: '/diretoria/$slug'
      path: '/diretoria/$slug'
      fullPath: '/diretoria/$slug'
      preLoaderRoute: typeof DiretoriaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorio/$slug': {
      id: '/relatorio/$slug'
      path: '/relatorio/$slug'
      fullPath: '/relatorio/$slug'
      preLoaderRoute: typeof RelatorioSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unidade/$slug': {
      id: '/unidade/$slug'
      path: '/unidade/$slug'
      fullPath: '/unidade/$slug'
      preLoaderRoute: typeof UnidadeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CartilhaRoute: CartilhaRoute,
  ConsolidadoRoute: ConsolidadoRoute,
  RelatorioConsolidadoRoute: RelatorioConsolidadoRoute,
  DiretoriaSlugRoute: DiretoriaSlugRoute,
  RelatorioSlugRoute: RelatorioSlugRoute,
  UnidadeSlugRoute: UnidadeSlugRoute,
  DiretoriaIndexRoute: DiretoriaIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
