/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CartilhaRouteImport } from './routes/cartilha'
import { Route as ConsolidadoRouteImport } from './routes/consolidado'
import { Route as RelatorioConsolidadoRouteImport } from './routes/relatorio-consolidado'
import { Route as RelatorioSlugRouteImport } from './routes/relatorio.$slug'
import { Route as UnidadeSlugRouteImport } from './routes/unidade.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CartilhaRoute = CartilhaRouteImport.update({
  id: '/cartilha',
  path: '/cartilha',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsolidadoRoute = ConsolidadoRouteImport.update({
  id: '/consolidado',
  path: '/consolidado',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatorioConsolidadoRoute = RelatorioConsolidadoRouteImport.update({
  id: '/relatorio-consolidado',
  path: '/relatorio-consolidado',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatorioSlugRoute = RelatorioSlugRouteImport.update({
  id: '/relatorio/$slug',
  path: '/relatorio/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const UnidadeSlugRoute = UnidadeSlugRouteImport.update({
  id: '/unidade/$slug',
  path: '/unidade/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/cartilha': typeof CartilhaRoute
  '/consolidado': typeof ConsolidadoRoute
  '/relatorio-consolidado': typeof RelatorioConsolidadoRoute
  '/relatorio/$slug': typeof RelatorioSlugRoute
  '/unidade/$slug': typeof UnidadeSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/cartilha': typeof CartilhaRoute
  '/consolidado': typeof ConsolidadoRoute
  '/relatorio-consolidado': typeof RelatorioConsolidadoRoute
  '/relatorio/$slug': typeof RelatorioSlugRoute
  '/unidade/$slug': typeof UnidadeSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/cartilha': typeof CartilhaRoute
  '/consolidado': typeof ConsolidadoRoute
  '/relatorio-consolidado': typeof RelatorioConsolidadoRoute
  '/relatorio/$slug': typeof RelatorioSlugRoute
  '/unidade/$slug': typeof UnidadeSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/cartilha'
    | '/consolidado'
    | '/relatorio-consolidado'
    | '/relatorio/$slug'
    | '/unidade/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/cartilha'
    | '/consolidado'
    | '/relatorio-consolidado'
    | '/relatorio/$slug'
    | '/unidade/$slug'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/cartilha'
    | '/consolidado'
    | '/relatorio-consolidado'
    | '/relatorio/$slug'
    | '/unidade/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  CartilhaRoute: typeof CartilhaRoute
  ConsolidadoRoute: typeof ConsolidadoRoute
  RelatorioConsolidadoRoute: typeof RelatorioConsolidadoRoute
  RelatorioSlugRoute: typeof RelatorioSlugRoute
  UnidadeSlugRoute: typeof UnidadeSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cartilha': {
      id: '/cartilha'
      path: '/cartilha'
      fullPath: '/cartilha'
      preLoaderRoute: typeof CartilhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consolidado': {
      id: '/consolidado'
      path: '/consolidado'
      fullPath: '/consolidado'
      preLoaderRoute: typeof ConsolidadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorio-consolidado': {
      id: '/relatorio-consolidado'
      path: '/relatorio-consolidado'
      fullPath: '/relatorio-consolidado'
      preLoaderRoute: typeof RelatorioConsolidadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorio/$slug': {
      id: '/relatorio/$slug'
      path: '/relatorio/$slug'
      fullPath: '/relatorio/$slug'
      preLoaderRoute: typeof RelatorioSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unidade/$slug': {
      id: '/unidade/$slug'
      path: '/unidade/$slug'
      fullPath: '/unidade/$slug'
      preLoaderRoute: typeof UnidadeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  CartilhaRoute: CartilhaRoute,
  ConsolidadoRoute: ConsolidadoRoute,
  RelatorioConsolidadoRoute: RelatorioConsolidadoRoute,
  RelatorioSlugRoute: RelatorioSlugRoute,
  UnidadeSlugRoute: UnidadeSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
